### ISSUE TITLE
[Feature] 공연 세부 내용 조회 API

### ISSUE THREAD

**Issue by yeGenieee** [f-lab-edu/Picketing#43]
## 목표
어떤 내용을 개발할지 적어주세요.

## 방법
목표를 이루기 위한 해결 방법을 대략적으로 설명 해주세요.

## 대안
위 방법 외에 대안이 있으면 작성해주세요.

## 주의사항
해결 과정에서 주의해야할 사항이 있다면 작성해주세요.

## etc
추가적으로 알아야할 내용을 작성해주세요.

**Comment by pollra** [comment]
해당 이슈의 마일스톤은 9-1 이지만 범위를 줄여서 해당 이슈는 추후에 처리하기로 이야기 되었습니다.
마일스톤에 등록된 항목은 변경되거나 나뉘지 않는 이상 옮기지 말라고 하셔서 일단 남겨둡니다
(cc: @f-lab-lion )
