### ISSUE TITLE
[Feature] 공연의 좌석 목록 조회 API

### ISSUE THREAD

**Issue by yeGenieee** [f-lab-edu/Picketing#44]
## 목표
좌석의 목록 조회 api 를 개발합니다.

## 방법
1. Api 개발

## 대안
-

## 주의사항
과설계 금물...!

## etc
-

**Comment by pollra** [comment]
해당 이슈의 마일스톤은 9-1 이지만 범위를 줄여서 해당 이슈는 추후에 처리하기로 이야기 되었습니다.
마일스톤에 등록된 항목은 변경되거나 나뉘지 않는 이상 옮기지 말라고 하셔서 일단 남겨둡니다
(cc: @f-lab-lion )
