### ISSUE TITLE
[Feature] 잔여 좌석 조회 API

### ISSUE THREAD

**Issue by yeGenieee** [f-lab-edu/Picketing#48]
## 목표
잔여 좌석을 조회하는 api 를 만듭니다

## 방법
아직 JPA 가 준비되지 않은 시점입니다.
메모리 저장을 활용하여 조회 api 를 구현합니다

## 대안
* JPA 가 도입 된 이후 적용합니다
* 실제 기능을 구현하지 않고 객체 설계만을 마칩니다

## 주의사항
* 저장 기능이 존재하지 않습니다. 저장 기능은 따로 구현하지 않고 진행합니다.

## etc
* 해당 이슈에서는 Discount 를 구현하지 않습니다.

**Comment by f-lab-lion** [comment]
pr에는 point가 `3`으로 셋팅되어있습니다. 이슈에는 `2`로 셋팅되어있는데 어느것이 맞는값인가요?
https://github.com/f-lab-edu/Picketing/pull/53

**Comment by pollra** [comment]
해당 이슈는 아래의 3개의 이슈로 분리되었습니다

* #58 
* #59 
* #60
