### ISSUE TITLE
[Feature] 공연 좌석 가격 조회 API 설계

### ISSUE THREAD

**Issue by yeGenieee** [f-lab-edu/Picketing#61]
## 목표
- 특정 공연에 대한 좌석 리스트 및 해당 좌석의 가격을 조회합니다

<img width="244" alt="Screenshot 2023-09-18 at 6 48 48 PM" src="https://github.com/f-lab-edu/Picketing/assets/23554779/ecda5073-ef85-4ab5-b02e-354bc7dd3337">

## 방법
- 기구현된 공연 좌석 도메인에 대한 설계를 바탕으로 API를 설계합니다 
- (#64 기본 작업 이후 작업을 할 수 있습니다)
- 필요한 필드가 있는 경우 추가합니다

### 결과물
- 비즈니스 로직 및 도메인 관련 로직을 제외한 컨트롤러 스켈레톤 코드
- 빈 컨트롤러에 반드시 포함되어야 하는 사항
    - API URL
    - Request 형식
    - Response 형식

## 대안
위 방법 외에 대안이 있으면 작성해주세요.

## 주의사항
해결 과정에서 주의해야할 사항이 있다면 작성해주세요.

## etc
추가적으로 알아야할 내용을 작성해주세요.

**Comment by f-lab-lion** [comment]
@yeGenieee @pollra 
api 설계를 하면 결과물이 어떤게 나와야할까요? 
설계가 완료되었다는것을 어떤 기준으로 삼을지 정해보면 좋겠습니다.

ex)
path / request / response ?
위 정보를 포함한 빈 컨트롤러?
api 문서?

**Comment by yeGenieee** [comment]
비즈니스 로직 및 도메인 로직을 제외한 컨트롤러의 스켈레톤을 설계 결과물로 지정하겠습니다 
- 빈 컨트롤러에 반드시 포함되어야 하는 사항
    - API URL
    - Request 형식
    - Response 형식
